module.exports.ROUTES = {
  LOGIN: 'Login',
  REGISTER: 'Register',
  DASHBOARD: 'Dashboard',
  PRODUCT: 'Product',
  PRODUCT_CREATE: 'ProductCreate',
  PRODUCT_EDIT: 'ProductEdit',
  PRODUCT_CATEGORY: 'ProductCategory',
  INVOICE: 'Invoice',
  PRODUCT_WAREHOUSE: 'ProductWarehouse',
  AppearanceSetting: 'AppearanceSetting',
  PageSetting: 'PageSetting',
  Entity: 'Entity',
  // User
  User: 'User',
  Post: 'Post',
  EditPost: 'EditPost',
  CreatePost: 'CreatePost',
  UserPermission: 'UserPermission',
  Role: 'Role',
  RolePermission: 'RolePermission',
  Redirect: 'Redirect',
  Init: 'Init',
}
